[package]
name = "webcasting_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
extend = "1.2.0"
js-sys = "0.3.61"
wasm-bindgen = "0.2.84"

[profile.release]
opt-level = "s"
